export enum NotificationEnum {
  // Appointment
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_STATUS_UPDATED_BY_CLIENT = 'APPOINTMENT_STATUS_UPDATED_BY_CLIENT',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',

  // AI Diagnosis
  AI_DIAGNOSIS = 'AI_DIAGNOSIS',

  // FOLLOW_UP_REMINDER
  FOLLOW_UP_REMINDER_BEFORE_TWO_DAYS = 'FOLLOW_UP_REMINDER_BEFORE_TWO_DAYS',
  FOLLOW_UP_REMINDER_TODAY = 'FOLLOW_UP_REMINDER_TODAY',

  // POST
  COMMENT_REPLY = 'COMMENT_REPLY',
  LIKE = 'LIKE',
}
