export enum NotificationEnum {
  // Appointment
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',

  // AI Diagnosis
  AI_DIAGNOSIS = 'AI_DIAGNOSIS',

  // FOLLOW_UP_REMINDER
  FOLLOW_UP_REMINDER = 'FOLLOW_UP_REMINDER',

  // COMMENT
  COMMENT_REPLY = 'COMMENT_REPLY',
}
