export enum ServiceEnum {
  PERIODIC_HEALTH_CHECK = 'PERIODIC_HEALTH_CHECK',
  MEDICAL_EXAMINATION = 'MEDICAL_EXAMINATION',
  VACCINATION = 'VACCINATION',
  DEWORMING = 'DEWORMING',
  ULTRASOUND_AND_TEST = 'ULTRASOUND_AND_TEST',
  SURGERY = 'SURGERY',
  EMERGENCY = 'EMERGENCY',
}
