export enum VeterinarySpecialtyEnum {
  GENERAL_EXAMINATION = 'GENERAL_EXAMINATION',
  INTERNAL_MEDICINE = 'INTERNAL_MEDICINE',
  SURGERY = 'SURGERY',
  ULTRASOUND = 'ULTRASOUND',
  VACCINATION_AND_PREVENTION = 'VACCINATION_AND_PREVENTION',
}
