// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2oMSKVxJua4kgf0FgMS8nQQ9JAEtV7k',
    appId: '1:482330049700:android:25c0efa2d291181ae37a31',
    messagingSenderId: '482330049700',
    projectId: 'petcarex-490104',
    storageBucket: 'petcarex-490104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcIPuHqT4xwi89kLHs_4aJ9OXU2RB5gQ',
    appId: '1:482330049700:ios:edfab3cf273eea9de37a31',
    messagingSenderId: '482330049700',
    projectId: 'petcarex-490104',
    storageBucket: 'petcarex-490104.firebasestorage.app',
    iosClientId: '482330049700-lv4dv3t6u1hnlmcbkiteqv9nfo7k3th2.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcarex',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQxckwXFdSIEcTxliHJ44dmHjIZo6eU84',
    appId: '1:482330049700:web:5f01d5bd31b8ef6ae37a31',
    messagingSenderId: '482330049700',
    projectId: 'petcarex-490104',
    authDomain: 'petcarex-490104.firebaseapp.com',
    storageBucket: 'petcarex-490104.firebasestorage.app',
    measurementId: 'G-3KQ7ZZ25P2',
  );

}